# -*- coding: utf-8 -*-
"""python_pizza.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/123IGYmyIwe_ODEgrWXJj6fR9A7b2XjO9
"""

import csv
from datetime import datetime
# importing the required libraries

# writing the menu to the file
with open("menu.txt", "w") as f:
    f.write("* Please choose a pizza base:\n")
    f.write("1: Classic Pizza 25TL \n")
    f.write("2: Margherita Pizza 20TL \n")
    f.write("3: Turkish Pizza 30TL \n")
    f.write("4: Plain Pizza 20TL \n")
    f.write("* and ingredient of your choice: \n")
    f.write("5: olives 3TL \n")
    f.write("6: Mushrooms 2TL \n")
    f.write("7: Goat Cheese 4TL \n")
    f.write("8: Meat 5TL \n")
    f.write("9: Onions 2TL \n")
    f.write("10: Corn 3TL \n")
    f.write("* Thank you! :) \n")

 # Create pizza class
class Pizza:
    def __init__(self):
        self.description = " Pizza"
        self.cost = 0

    def get_description(self):
        return self.description

    def get_cost(self):
        return self.cost
    
class classicPizza(Pizza):
    def __init__(self):
        super().__init__()
        self.description = "Classic pizza"
        self.cost = 25

class MargheritaPizza(Pizza):
    def __init__(self):
        super().__init__()
        self.description = "Margherita Pizza"
        self.cost = 20

class TurkishPizza(Pizza):
    def __init__(self):
        super().__init__()
        self.description = "Turkish pizza"
        self.cost = 30

class plainPizza(Pizza):
    def __init__(self):
        super().__init__()
        self.description = "Plain pizza"
        self.cost = 20

# create decorator class
class Decorator(Pizza):
    def __init__(self, component):
        self.component = component

    def get_cost(self):
        return self.component.get_cost() + Pizza.get_cost(self)

    def get_description(self):
        return self.component.get_description() + ' ' + Pizza.get_description(self)



class olives(Decorator):
    def __init__(self, component):
        super().__init__(component)
        self.description = "Olives"
        self.cost = 3

class mushrooms(Decorator):
    def __init__(self, component):
        super().__init__(component)
        self.description = "Mushrooms"
        self.cost = 2

class goatcheese(Decorator):
    def __init__(self, component):
        super().__init__(component)
        self.description = "Goat Cheese"
        self.cost = 4

class meat(Decorator):
    def __init__(self, component):
        super().__init__(component)
        self.description = "Meat"
        self.cost = 5

class onions(Decorator):
    def __init__(self, component):
        super().__init__(component)
        self.description = "Onions"
        self.cost = 2

class corn(Decorator):
    def __init__(self, component):
        super().__init__(component)
        self.description = "Corn"
        self.cost = 3

from datetime import datetime

def main():
    # writing the menu to the file
    with open("menu.txt", "r") as f:
        print(f.read())

# getting the pizza type and ingredients from the user
    while True:
        try:
            pizza_choice = int(input("Please choose a pizza base(1-4): "))
            if pizza_choice < 1 or pizza_choice > 4:
                raise ValueError
            break
        except ValueError:
            print(" Invalid choice! ")
    
    while True:
        try:
            ingredient_choice = int(input("Please choose an ingredient(5-10): "))
            if ingredient_choice < 5 or ingredient_choice > 10:
                raise ValueError
            break
        except ValueError:
            print(" Invalid choice! ")
    

    if pizza_choice == 1:
      pizza = classicPizza()
    elif pizza_choice == 2:
      pizza = MargheritaPizza()
    elif pizza_choice == 3:
      pizza = TurkishPizza()
    elif pizza_choice == 4:
      pizza = plainPizza()


    if ingredient_choice == 5:
      ingredient = olives(pizza)
    elif ingredient_choice == 6:
      ingredient = mushrooms(pizza)
    elif ingredient_choice == 7:
      ingredient = goatcheese(pizza)
    elif ingredient_choice == 8:
      ingredient = meat(pizza)
    elif ingredient_choice == 9:
      ingredient = onions(pizza)
    elif ingredient_choice == 10:
      ingredient = corn(pizza)

    # Calculate total cost
    total_cost = ingredient.get_cost()

    name = input("Please enter your name: ") # getting the name from the user
    tc_no = input("Please enter your ID number: ") # getting the id number from the user
    credit_card_no = input("Please enter your credit card number: ") # getting the credit card number from the user
    credit_card_password = input("Please enter your credit card password: ") # getting the credit card number from the user

    # Save order to Orders_Database.csv
    with open("Orders_Database.csv", "a") as f:
        writer = csv.writer(f)
        writer.writerow([name, tc_no, credit_card_no, ingredient.get_description(), datetime.now().strftime("%Y-%m-%d %H:%M:%S"), credit_card_password])

    print("Thank you for your order :) ")
main()